-- Migration: seed local data exported from localStorage
-- Generated by scripts/generate-seed-migration.js from seed\store.example.json
ALTER TABLE applications
  ADD COLUMN IF NOT EXISTS interview_date date,
  ADD COLUMN IF NOT EXISTS interview_time time,
  ADD COLUMN IF NOT EXISTS final_interview_date date,
  ADD COLUMN IF NOT EXISTS final_interview_time time,
  ADD COLUMN IF NOT EXISTS is_deployed boolean default false;

INSERT INTO hr_users (id, email, password, name, phone)
VALUES
  ('11111111-1111-1111-1111-111111111111', 'hr@example.com', 'change-me', 'HR Admin', '09170000000')
ON CONFLICT (id) DO NOTHING
;

INSERT INTO users (id, email, password, name, phone, role)
VALUES
  ('22222222-2222-2222-2222-222222222222', 'intern@example.com', 'change-me', 'Sample Intern', '09170000001', 'intern')
ON CONFLICT (id) DO NOTHING
;

INSERT INTO applications (id, user_id, name, email, phone, course, school, cv_name, cover_name, ojt_type, hours_required, source, status, applied_date, quarter, department, supervisor, schedule, start_date, company_docs, school_docs, interview_date, interview_time, final_interview_date, final_interview_time, is_deployed)
VALUES
  ('33333333-3333-3333-3333-333333333333', '22222222-2222-2222-2222-222222222222', 'Sample Intern', 'intern@example.com', '09170000001', 'BS Information Technology', 'Sample University', 'cv.pdf', 'portfolio.pdf', 'required', 480, 'LinkedIn', 'accepted', '2026-04-01', 'Q2-2026', 'IT', 'To be assigned', 'Mon-Fri, 8:00 AM - 5:00 PM', '2026-04-15', '{"offer_letter":"submitted"}'::jsonb, '[{"id":"sd_001","name":"Endorsement Letter","fileName":"endorsement.pdf","status":"submitted","signedBy":null}]'::jsonb, '2026-04-05', '10:00', '2026-04-10', '14:00', FALSE)
ON CONFLICT (id) DO NOTHING
;

INSERT INTO dtr_entries (id, app_id, date, time_in, time_out, type)
VALUES
  ('44444444-4444-4444-4444-444444444444', '33333333-3333-3333-3333-333333333333', '2026-04-16', '08:00', '17:00', 'work')
ON CONFLICT (id) DO NOTHING
;

INSERT INTO school_activities (id, app_id, name, description, status, type)
VALUES
  ('55555555-5555-5555-5555-555555555555', '33333333-3333-3333-3333-333333333333', 'Career Talk', 'School activity', 'approved', 'school')
ON CONFLICT (id) DO NOTHING
;

INSERT INTO messages (id, app_id, sender, text, time)
VALUES
  ('66666666-6666-6666-6666-666666666666', '33333333-3333-3333-3333-333333333333', 'hr', 'Welcome to PRIME!', '2026-04-16T09:00:00Z')
ON CONFLICT (id) DO NOTHING
;

INSERT INTO email_templates (id, name, subject, body)
VALUES
  ('tmpl_initial_interview', 'Initial Interview', 'Interview Schedule', 'Hello {name}, your interview is on {date} at {time}.')
ON CONFLICT (id) DO NOTHING
;

INSERT INTO company_documents (id, name, description, type)
VALUES
  ('offer_letter', 'Offer Letter', 'Signed offer letter', 'company')
ON CONFLICT (id) DO NOTHING
;

INSERT INTO dept_slots (department, slots)
VALUES
  ('IT', 3),
  ('HR', 1)
ON CONFLICT (department) DO UPDATE SET slots = EXCLUDED.slots
;

INSERT INTO quarter_settings (id, current)
VALUES
  (1, 'Q2-2026')
ON CONFLICT (id) DO UPDATE SET current = EXCLUDED.current
;
